### PR TITLE
permanently denied permission fix

### PR DESCRIPTION
**Pull request by fazakasreka**

### CODE REVIEW

**Review by radl97 — APPROVED** [review]
I don't understand the half of it. Have fun!

**Comment by fazakasreka** [comment]
@radl97 áll még a mai tali?

**Comment by radl97** [comment]
Oh, elfelejtettem. Umm sztem ezt nem fogjatok latni, irok FBn

On Tuesday, October 8, 2024, Réka Fazakas ***@***.***> wrote:
> @radl97 áll még a mai tali?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci3.googleusercontent.com/meips/ADKq_NYUHhYjr5Usk_Vo06j_Xb2yKTiLKMslUGWrjX63cA2bILcaxe2EYNhyUc7jjWVgg3cdVRYOmG2FBd9J2RCal7_SYsXEYk90LMFSJbdnh0Qkk3Sl4g9_uer31KunqXc1f_nOChl6xYWa08LkOxBuE5zofhoK9qyJ3PENczmeBaBr8wczjoT8m5rJHXvltcNNc5f84AMYiDyQqqywRX2wQSJxN62csBKoclza-AvlUGB8d7IfG2j7q-M=s0-d-e1-ft#https://github.com/notifications/beacon/AB4DZUF7OUK6BZJT232RW53Z2O3GRA5CNFSM6AAAAABPR5VCCGWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTUPAXRQC.gif>Message
ID: ***@***.***>

**Comment by radl97** [comment]
(de raerek, csak picit kesek. Megbeszeltuk, hogy mondjuk Allee?)

On Tuesday, October 8, 2024, L Radnai ***@***.***> wrote:
> Oh, elfelejtettem. Umm sztem ezt nem fogjatok latni, irok FBn
>
> On Tuesday, October 8, 2024, Réka Fazakas ***@***.***>
wrote:
>> @radl97 áll még a mai tali?
>>
>> —
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>> You are receiving this because you were mentioned.<
https://ci3.googleusercontent.com/meips/ADKq_NYUHhYjr5Usk_Vo06j_Xb2yKTiLKMslUGWrjX63cA2bILcaxe2EYNhyUc7jjWVgg3cdVRYOmG2FBd9J2RCal7_SYsXEYk90LMFSJbdnh0Qkk3Sl4g9_uer31KunqXc1f_nOChl6xYWa08LkOxBuE5zofhoK9qyJ3PENczmeBaBr8wczjoT8m5rJHXvltcNNc5f84AMYiDyQqqywRX2wQSJxN62csBKoclza-AvlUGB8d7IfG2j7q-M=s0-d-e1-ft#https://github.com/notifications/beacon/AB4DZUF7OUK6BZJT232RW53Z2O3GRA5CNFSM6AAAAABPR5VCCGWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTUPAXRQC.gif>Message
ID: ***@***.***>

**Pull request merged**
